### ISSUE TITLE
人员管理 --> 修改

### ISSUE THREAD

**Issue by JackyReal** [microlcl/scheme_repo#112]
500 错误

10:52:08.616 [http-bio-8080-exec-8] INFO  c.eastteam.myprogram.web.AuthFilter - in filter: uri=/account/show/%E6%B5%8B%E8%AF%95
10:52:08.662 [http-bio-8080-exec-8] ERROR 500.jsp - null
java.lang.NullPointerException: null
    at com.eastteam.myprogram.web.account.AccountController.getAllRolesList(AccountController.java:179) ~[AccountController.class:na]
    at com.eastteam.myprogram.web.account.AccountController.update(AccountController.java:129) ~[AccountController.class:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_45]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.7.0_45]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.7.0_45]

问题重现步骤 ：
1. 创建一个新用户，登录名是汉语
2. 用这个新用户登陆，然后 “修改”

初步分析：
1）。 修改的时候前台过来的汉语登录名做了encode
2）。查询数据库，没有做decode 出来？？ 然后没有拿出记录，结果程序里面对空指针异常也没考虑的样子吧
。。。。。。。

**Comment by microlcl** [comment]
这个是中文的url没有encode，已经fix了
