### ISSUE TITLE
进店管理 ： 非初次到访

### ISSUE THREAD

**Issue by JackyReal** [microlcl/scheme_repo#134]
提交保存的时候500 错误

14:36:01.877 [http-bio-8080-exec-6] INFO  c.eastteam.myprogram.web.AuthFilter - in filter: uri=/visit/update/null
14:36:01.882 [http-bio-8080-exec-6] INFO  c.e.m.web.visit.VisitController - in visit controller: update 
14:36:01.901 [http-bio-8080-exec-6] ERROR 500.jsp - For input string: "null"
java.lang.NumberFormatException: For input string: "null"
    at java.lang.NumberFormatException.forInputString(Unknown Source) ~[na:1.7.0_45]
    at java.lang.Long.parseLong(Unknown Source) ~[na:1.7.0_45]
    at java.lang.Long.parseLong(Unknown Source) ~[na:1.7.0_45]
    at com.eastteam.myprogram.service.visit.VisitService.getVisitWithAnswer(VisitService.java:252) ~[VisitService.class:na]
    at com.eastteam.myprogram.service.visit.VisitService$$FastClassByCGLIB$$c8ca06e3.invoke(<generated>) ~[spring-core-3.2.3.RELEASE.jar:na]
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:698) ~[spring-aop-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) ~[spring-aop-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96) ~[spring-tx-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260) ~[spring-tx-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94) ~[spring-tx-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:631) ~[spring-aop-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at com.eastteam.myprogram.service.visit.VisitService$$EnhancerByCGLIB$$f93e176e.getVisitWithAnswer(<generated>) ~[spring-core-3.2.3.RELEASE.jar:na]
    at com.eastteam.myprogram.web.visit.VisitController.updateVisit(VisitController.java:184) ~[VisitController.class:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_45]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.7.0_45]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.7.0_45]

**Comment by 118yangbin** [comment]
已经解决。
