### ISSUE TITLE
需求管理模块 ： 增加到访记录

### ISSUE THREAD

**Issue by JackyReal** [microlcl/scheme_repo#139]
500 错误

重现步骤，先增加一个到访记录，然后再添加一个 ：  这个地方，如果是对同一条进店流水做“增加到访记录”， 那么到访记录和问卷都是修改操作.
### Cause: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "PRIMARY_KEY_D ON PUBLIC.PAPER_ANSWERS(BUSINESS_ID, PAPER_ID, QUESTION_ID)"; SQL statement:

insert into paper_answers(business_id, paper_id, question_id, answer) values
        (concat('V',?),?,?,?); [23505-172]
; SQL []; Unique index or primary key violation: "PRIMARY_KEY_D ON PUBLIC.PAPER_ANSWERS(BUSINESS_ID, PAPER_ID, QUESTION_ID)"; SQL statement:
insert into paper_answers(business_id, paper_id, question_id, answer) values
        (concat('V',?),?,?,?); [23505-172]; nested exception is org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "PRIMARY_KEY_D ON PUBLIC.PAPER_ANSWERS(BUSINESS_ID, PAPER_ID, QUESTION_ID)"; SQL statement:
insert into paper_answers(business_id, paper_id, question_id, answer) values
        (concat('V',?),?,?,?); [23505-172]
    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:245) ~[spring-jdbc-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72) ~[spring-jdbc-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:71) ~[mybatis-spring-1.2.0.jar:1.2.0]
    at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:364) ~[mybatis-spring-1.2.0.jar:1.2.0]
    at com.sun.proxy.$Proxy14.insert(Unknown Source) ~[na:na]
    at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:236) ~[mybatis-spring-1.2.0.jar:1.2.0]
    at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:46) ~[mybatis-3.2.2.jar:3.2.2]
    at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:43) ~[mybatis-3.2.2.jar:3.2.2]
    at com.sun.proxy.$Proxy25.updateVisitAnswers(Unknown Source) ~[na:na]
    at com.eastteam.myprogram.service.visit.VisitService.saveVisit(VisitService.java:120) ~[VisitService.class:na]
    at com.eastteam.myprogram.service.visit.VisitService$$FastClassByCGLIB$$c8ca06e3.invoke(<generated>) ~[spring-core-3.2.3.RELEASE.jar:na]
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:698) ~[spring-aop-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) ~[spring-aop-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96) ~[spring-tx-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260) ~[spring-tx-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94) ~[spring-tx-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:631) ~[spring-aop-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at com.eastteam.myprogram.service.visit.VisitService$$EnhancerByCGLIB$$55cf208e.saveVisit(<generated>) ~[spring-core-3.2.3.RELEASE.jar:na]
    at com.eastteam.myprogram.web.visit.VisitController.save(VisitController.java:135) ~[VisitController.class:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_45]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.7.0_45]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.7.0_45]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.7.0_45]
    at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:219) ~[spring-web-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132) ~[spring-web-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104) ~[spring-webmvc-3.2.3.RELEASE.jar

**Comment by lss0720** [comment]
这个问题已经解决。并且所有的paper_answers都改了逻辑、businessId在service类里面进行合成、然后判断是V（到访）还是R(回访)。

**Comment by microlcl** [comment]
功能有问题，我新增一个defect
