### ISSUE TITLE
进店管理模块 --> 非初次到访，保存失败

### ISSUE THREAD

**Issue by JackyReal** [microlcl/scheme_repo#70]
另外到访人数不需要必须录入

00:39:55.550 [http-bio-8080-exec-5] ERROR 500.jsp - null
java.lang.NullPointerException: null
    at com.eastteam.myprogram.service.visit.VisitService.saveVisit(VisitService.java:133) ~[VisitService.class:na]
    at com.eastteam.myprogram.service.visit.VisitService$$FastClassByCGLIB$$c8ca06e3.invoke(<generated>) ~[spring-core-3.2.3.RELEASE.jar:na]
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:698) ~[spring-aop-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) ~[spring-aop-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96) ~[spring-tx-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260) ~[spring-tx-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94) ~[spring-tx-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:631) ~[spring-aop-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at com.eastteam.myprogram.service.visit.VisitService$$EnhancerByCGLIB$$5909a5ea.saveVisit(<generated>) ~[spring-core-3.2.3.RELEASE.jar:na]
    at com.eastteam.myprogram.web.visit.VisitController.save(VisitController.java:137) ~[VisitController.class:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_45]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.7.0_45]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.7.0_45]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.7.0_45]

**Comment by lss0720** [comment]
已经解决、这是因为德泉后续添加的visitFormBean.getOperator()为空导致的。已加判断。
