### ISSUE TITLE
产品管理模块 ： 产品查看--> 看不到产品图片

### ISSUE THREAD

**Issue by JackyReal** [microlcl/scheme_repo#87]
重现步骤：
1. 新建角色A，赋予产品模块所有功能，包括 “查看”。
   2.新建用户a，赋予角色A
2. 登陆用户a

产品图片看不到，后台有异常：

Sep 13, 2014 10:45:19 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [springServlet] in context with path [/myprogram] threw exception
com.eastteam.myprogram.web.AuthorizationException: auth failed:/category/api/getChildren/getProductAttribute
    at com.eastteam.myprogram.web.AuthFilter.doFilter(AuthFilter.java:73)
    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
    at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

22:45:19.713 [http-bio-8080-exec-2] INFO  c.eastteam.myprogram.web.AuthFilter - in filter: uri=/category/api/getChildren/getProductAttribute
22:45:19.714 [http-bio-8080-exec-2] INFO  c.eastteam.myprogram.web.AuthFilter - 没有授权访问此资源
22:45:31.289 [http-bio-8080-exec-7] INFO  c.eastteam.myprogram.web.AuthFilter - in filter: uri=/product/list

**Comment by microlcl** [comment]
Root cause:
/category/api/getChildren/getProductAttribute 没有配置到这个产品查看权限里面

**Comment by JackyReal** [comment]
这个功能其实不需要做权限控制？ 因为对用户其实是无意义的，属于系统运行需要的功能？
做到权限控制里面貌似也不友好的样子

**Comment by microlcl** [comment]
Jacky说的对，我把所有REST service都弄到那个authFilter的ingore list里面了。
此问题fix了
