### ISSUE TITLE
任务管理：新增task里面的upload不好用

### ISSUE THREAD

**Issue by microlcl** [microlcl/scheme_repo#93]
在新增task页面，upload不好用：
18:25:27.987 [29947292@qtp-12934710-5] INFO  c.eastteam.myprogram.web.AuthFilter - in filter: uri=/task/upload
18:25:28.069 [29947292@qtp-12934710-5] INFO  c.e.m.web.task.TaskController - 文件保存路径：C:/Users/IBM_ADMIN/workspace/myprogram/WebContent/plupload/attachment/
18:25:28.069 [29947292@qtp-12934710-5] INFO  c.e.m.web.task.TaskController - 文件名称：bjh6iayx044os5jh7cxxoxfr_mypic1.jpg
18:25:28.276 [29947292@qtp-12934710-5] ERROR 500.jsp - null
java.lang.NumberFormatException: null
    at java.lang.Long.parseLong(Long.java:375) ~[na:1.6.0_43]
    at java.lang.Long.parseLong(Long.java:468) ~[na:1.6.0_43]
    at com.eastteam.myprogram.web.task.TaskController.plupload(TaskController.java:176) ~[bin/:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_43]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_43]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_43]
    at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_43]
    at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:219) ~[spring-web-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132) ~[spring-web-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104) ~[spring-webmvc-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:745) ~[spring-webmvc-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:686) ~[spring-webmvc-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80) ~[spring-webmvc-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:925) [spring-webmvc-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:856) [spring-webmvc-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:936) [spring-webmvc-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:838) [spring-webmvc-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727) [servlet-api-2.5-20081211.jar:na]
    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:812) [spring-webmvc-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820) [servlet-api-2.5-20081211.jar:na]
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511) [jetty-6.1.26.jar:6.1.26]
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1221) [jetty-6.1.26.jar:6.1.26]
    at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129) [sitemesh-2.4.2.jar:na]
    at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77) [sitemesh-2.4.2.jar:na]
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212) [jetty-6.1.26.jar:6.1.26]
    at com.eastteam.myprogram.web.AuthFilter.doFilter(AuthFilter.java:80) [bin/:na]
    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346) [spring-web-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259) [spring-web-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212) [jetty-6.1.26.jar:6.1.26]
    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88) [spring-web-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212) [jetty-6.1.26.jar:6.1.26]
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399) [jetty-6.1.26.jar:6.1.26]
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216) [jetty-6.1.26.jar:6.1.26]
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182) [jetty-6.1.26.jar:6.1.26]
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766) [jetty-6.1.26.jar:6.1.26]
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450) [jetty-6.1.26.jar:6.1.26]
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152) [jetty-6.1.26.jar:6.1.26]
    at org.mortbay.jetty.Server.handle(Server.java:326) [jetty-6.1.26.jar:6.1.26]
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542) [jetty-6.1.26.jar:6.1.26]
    at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945) [jetty-6.1.26.jar:6.1.26]
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756) [jetty-6.1.26.jar:6.1.26]
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218) [jetty-6.1.26.jar:6.1.26]
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404) [jetty-6.1.26.jar:6.1.26]
    at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410) [jetty-6.1.26.jar:6.1.26]
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582) [jetty-util-6.1.26.jar:6.1.2

**Comment by microlcl** [comment]
这个是功能性问题，需要尽快fix。
Thanks

**Comment by microlcl** [comment]
YangBin，还有一个问题,关于上传路径的问题， 我在配置文件里面配置了一个
upload.path.relative=true
这个属性是放在测试的配置文件里面：
src\test\resources\application.test.properties
也就是我们本地开发用到的配置文件
如果有这个属性，并且为true，就用相对路径来保存上传的文件。否则，就用生产环境的配置文件里面的属性：
// configuration for uploading feature:
upload.path=C:/Users/IBM_ADMIN/workspace/myprogram/WebContent/plupload
来保存文件
这样就可以方便我们checkout下来的代码，不会因为path问题而不能run

**Comment by microlcl** [comment]
想了一下，可以不要upload.path.relative这个参数。
直接在src\test\resources\application.test.properties把upload.path配置从空值
upload.path=
就行了
在代码中判断：
if (upload.path 为空) {
上传到相对路径
} else {
上传到${upload.path}
}

**Comment by microlcl** [comment]
可以参考MediaController.plupload()方法的实现：
    public String plupload(@RequestParam MultipartFile file, HttpSession session, String name) {
        String realPath = getUploadPath();
        logger.info("upload path from config file: " + realPath);
        // upload.path在test配置文件中vlaue为空,所以取相对路径
        if (StringUtils.isBlank(realPath)) {
            realPath = WebUtils.getRealPath(session) + "/plupload";
        }
        logger.info("real path for upload: " + realPath);
        String filename = session.getId() + "_" + name;
        // for test env
        mediaService.saveFile(file, realPath, filename);
        // for Prod env
//      mediaService.saveFile(file, null, filename);
        return "";
    }

**Comment by 118yangbin** [comment]
1.异常已经解决。
2.路径问题已经参考上面这个改过来了。如果upload.path在test配置文件中vlaue为空,所以取相对路径。
